### ISSUE TITLE
Error Page Showing on Switch

### ISSUE THREAD

**Issue by JoshGreenHWD** [johnbillion/user-switching#140]
Hi all, we're having an issue with the plugin where when we switch to a customer and try and switch back to admin and error page is coming up. However when we try again and press the same button the plugin works as intended.

**Step 1:**
<img width="320" alt="Screenshot 2024-10-10 at 09 24 06" src="https://github.com/user-attachments/assets/23e4b907-b640-4e96-b156-66f22c9c27b0">

**Step 2**
<img width="314" alt="Screenshot 2024-10-10 at 09 24 16" src="https://github.com/user-attachments/assets/2b51de5b-ad2d-436f-91a3-24d9d48ac52a">

**Step 3 (after pressing the link from Step 1)**
<img width="142" alt="Screenshot 2024-10-10 at 09 24 53" src="https://github.com/user-attachments/assets/f0a5bb20-cea2-4080-8cb7-b127ce352424">

Any light you guys could shed on this would be appreciated. We're using a custom template who's source code I cannot share. The user-switching plugin being used on at least 10 sites right now and all are getting the same error.

**Comment by johnbillion** [comment]
There's a high chance this is caused by a caching implementation that is either caching the full page when it shouldn't or caching something in the object cache when it shouldn't, which results in you seeing a link to switch that isn't valid.

Your best bet is to try deactivating any plugins relating to caching or performance, and see if you can find the culprit.

Good luck and please let me know if you find out what the problem is.
