### ISSUE TITLE
Sessions not cleared

### ISSUE THREAD

**Issue by szepeviktor** [johnbillion/user-switching#20]
Could it be that after few switches I have multiple sessions?

Using User Session Control.

**Comment by johnbillion** [comment]
Yeah this is an issue that I've known about since sessions were introduced into WordPress.

User Switching doesn't inherit the old session when you switch back to the original user, which results in an extra session being created when you switch back.

In addition, I don't think the session of the user that you switched to gets cleared when your switch back.

I've looked at this a few times but it's actually a lot more complicated than it might seem, mostly due to the fact that the sessions API doesn't expose public access to sessions by their key, only by their hash.

I'll see if I can find some time to look into it again soon.

**Comment by szepeviktor** [comment]
Thank you for your work.

**Comment by uthpala-era** [comment]
When the plugin is used in a woocommerce site, not the switched users cart is displayed, but the original users. So is this the same issue regarding sessions.
We are in a pretty needy situation to allow admin to switch to customer account and add items to thier cart on behalf of the customer.

**Comment by szepeviktor** [comment]
There could be a plugin for that...

**Comment by johnbillion** [comment]
I'm pretty sure that issue is related to WooCommerce cookies, not WordPress user sessions. https://wordpress.org/support/topic/user-switching-plugin-woocommerce-not-clearing-cookies/

**Comment by johnbillion** [comment]
I tried working on this again recently but ran into a bunch of issues. I am determined to fix this at some point.

**Comment by johnbillion** [comment]
I've started to address this in #27. Lots still to do.

**Comment by johnbillion** [comment]
Fixed in #27.
