### ISSUE TITLE
Intermittent patchy performance

### ISSUE THREAD

**Issue by lordmatt** [johnbillion/user-switching#26]
I'm not sure if this is a bug with this plugin, an issue with BuddyPress/BBPress, a multi-site thing, or a cache problem. So I'm just mentioning it in case there is anything that can be done.

When I switch users some areas of the main site, BBPress and BuddyPress mostly, show me as logged out. Hitting refresh a lot or adding in a random query string busts the problem (which makes me think it could be a cache issue). However, some pages do this more than others. For example, the forum overview is almost always "logged out" while the forums themselves - only sometimes.

As I say, I cannot be sure this is a problem at this end of things but the issues only show up while I am using this plugin to act as another user.

**Comment by johnbillion** [comment]
Does the issue still occur if you manually sign in as another user instead of using User Switching to switch to the user?

There's not really anything in User Switching that would cause such behaviour. It switches you to another user and sets a cookie that records the ID of the user you switched from, so you can switch back, and that's about it.

Let me know what happens with the manual switching.
