### ISSUE TITLE
User Switching and Duo Security

### ISSUE THREAD

**Issue by soderlind** [johnbillion/user-switching#6]
(I usally don't do this, but I've x-posted this question on https://wordpress.org/support/topic/user-switching?replies=1#post-6749104)

On a multisite, with duo security enabled. When I switch to a user I get the duo security login page ("approve with your phone"). The phone number is for the user I'm trying to switch to.

Any idea how I can make duo secuity work together with User Switching?

**Comment by johnbillion** [comment]
User Switching plays well with other two-factor plugins such as [Google Authenticator](https://wordpress.org/plugins/google-authenticator/), so I'm guessing that Duo Security might be a bit over zealous about when it requests a 2FA code.

**Comment by johnbillion** [comment]
I think maybe User Switching can actually be made to play more nicely with 2FA plugins. I'll look into it when I get some time.

**Comment by johnbillion** [comment]
I've just been looking at the Duo Security plugin for WordPress. It doesn't play nicely with User Switching because of the way it re-authenticates a user after they've logged in (or been switched to).

I've just written a [User Switching for Duo Security add-on-plugin](https://github.com/johnbillion/user-switching-duo-security) which makes Duo Security play nicely with User Switching. It's only a few lines of code.

Give that plugin a whirl!
