### ISSUE TITLE
User switching fails on certain providers

### ISSUE THREAD

**Issue by munsterlander** [johnbillion/user-switching#60]
I have your awesome plugin running on several different hosts and it works great!  Recently, we were hired to do a site on Dreamhost.  For whatever reason, the user switching works some of the time and not the others.  Specifically, logged in as an admin, I go to switch to a user and it takes me to the admin Dashboard saying switched to my admin account.  I find this usually happens after I switch to one user, go back to myself and then try to go to another.  If I wait a few minutes, it works. 
 Any thoughts as to why this may be?

Everything is the most current version.

**Comment by johnbillion** [comment]
This sort of problem is usually caused by caching at some layer.

Try deactivating any cache plugins first (including mu-plugins and dropins) to see if the problem goes away.

If that doesn't work, try deactivating your other plugins one by one and switch to one of the default themes such as Twenty Twenty.
