### ISSUE TITLE
Not working on production

### ISSUE THREAD

**Issue by antonio-petricca** [johnbillion/user-switching#68]
It does not working on the production website. Instead it works for the staging environment (same server).

How can I debug it?

Thank you so much!

**Comment by johnbillion** [comment]
What exactly doesn't work? Can you provide some info?

**Comment by antonio-petricca** [comment]
I click on the siwtch link, but the logger user remain the same (the admin).

**Comment by johnbillion** [comment]
This could be a problem with a caching plugin, or with your cookies. Try clearing all your cookies and of that doesn't work then try deactivating any caching or security plugins.

**Comment by johnbillion** [comment]
I'm very sorry but I'm not sure what the issue could be, and the underlying issue is most likely not with User Switching itself. The plugin is used on 100,000+ sites and I've only seen this reported 4 or 5 times in the last 10 years, and each time it's been due to either a caching plugin or a security plugin interfering with the request to switch the user. I would recommend investigating what differences there are between your staging site and your production site.

**Comment by antonio-petricca** [comment]
Why you don't answer my question: "is there a way to debug you plugin?"

**Comment by johnbillion** [comment]
If User Switching shows you an error message then yes you can debug this. If there's no error message, then it means the problem lies elsewhere, as I said most likely in a caching or security plugin that is preventing the request even making it to the User Switching plugin.
