### ISSUE TITLE
Is there a way to distinguish user switching from regular logins?

### ISSUE THREAD

**Issue by therealgilles** [johnbillion/user-switching#69]
I would like to keep tracks of regular user logins and filter out user switching logins. Is there a way to do that? Thanks for any advice :)

**Comment by johnbillion** [comment]
Yep this is possible. If you use the `authenticate` filter or the `wp_login` action then those only fire when a user actually logs in, not when a user switches.

If you use the `set_auth_cookie` action then that will also fire when a user switches. In that case I don't believe you can determine at that point whether the user is logging in or switching because the corresponding `$_COOKIE` values won't be updated at that point.
